
services:
  auth_redis:
    container_name: auth_redis
    image: docker.io/bitnami/redis:5.0.14
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - auth_network
    ports:
      - '6379:6379'

  postgres_db:
    container_name: postgres_db
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=auth_sprint
      - POSTGRES_PASSWORD=auth_sprint
      - POSTGRES_DB=auth_sprint_test
    volumes:
      - ../postgres_data:/var/lib/postgresql/data/
    networks:
      - auth_network
    ports:
      - "5432:5432"

  flask_app:
    container_name: flask_app
    build:
      context: ./
      dockerfile: Dockerfile
    networks:
      - auth_network
    ports:
      - '5000:5000'
    depends_on:
      - postgres_db
      - auth_redis
    env_file:
      - ./.env

  nginx:
    container_name: nginx
    image: nginx:1.20.1-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/site.conf:/etc/nginx/conf.d/site.conf:ro
    ports:
      - "80:80"
    networks:
      - auth_network
    depends_on:
      - flask_app

  tests:
    container_name: tests
    build:
      context: ./
      dockerfile: DockerfileForTests
    entrypoint: >
      sh -c "python tests/functional/utils/wait_for_redis.py
      && pytest . -vv"
    networks:
      - auth_network
    depends_on:
      - postgres_db
      - flask_app
      - nginx
    env_file:
      - ./.env

networks:
  auth_network:
